export const TERMINAL_COMMANDS = [
  'play',
  'resume',
  'pause',
  'stop',
  'next',
  'n',
  'prev',
  'p',
  'shuffle',
  'repeat',
  'artist',
  'artist clear',
  'play artist',
  'list',
  'ls',
  'ls -la',
  'ls -ra',
  'ls -th',
  'music list',
  'music clear',
  'music -- path',
  'music config',
  'sources',
  'source local',
  'source radio',
  'radio',
  'radio list',
  'radio search',
  'radio search country',
  'radio add',
  'radio edit',
  'radio remove',
  'radio clear',
  'radio export',
  'radio import',
  'radio import external',
  'radio pins',
  'radio pin',
  'radio unpin',
  'radio history',
  'radio search music',
  'fm',
  'home',
  'exit',
  'quit',
  'help',
  'h',
  '?',
  ':q',
  'status',
  'info',
  'vol',
  '+',
  '=',
  '-',
  'mute',
  'unmute',
  'clear',
  'clear playback',
  'clear all',
  'copy error',
  'version',
  'cat now_playing.txt',
  'cat now_playing.json',
  'open now-playing',
  'open now-playing-json',
  'open visualizer',
  'open controls',
  'visualizer ascii',
  'visualizer pixel',
  'visualizer --mode=ascii',
  'visualizer --mode=pixel',
  'theme list',
  'theme use default',
  'theme use tokyo-night',
  'theme use dark-soul',
  'theme use synthwave',
  'theme use dark-petroleum-blue',
  'theme use shell-pink',
  'theme use claude-code',
  'settings radio.static on',
  'settings radio.static off',
]
