export const TERMINAL_COMMANDS = [
  'play',
  'resume',
  'pause',
  'stop',
  'next',
  'n',
  'prev',
  'p',
  'shuffle',
  'repeat',
  'list',
  'ls',
  'ls -la',
  'ls -ra',
  'ls -th',
  'music list',
  'music clear',
  'music -- path',
  'music config',
  'sources',
  'source local',
  'source radio',
  'radio',
  'radio list',
  'radio search',
  'radio add',
  'radio edit',
  'radio remove',
  'radio clear',
  'radio export',
  'radio import',
  'radio import external',
  'radio pins',
  'radio pin',
  'radio unpin',
  'radio history',
  'radio search music',
  'fm',
  'home',
  'exit',
  'quit',
  'help',
  'h',
  '?',
  ':q',
  'status',
  'info',
  'vol',
  '+',
  '=',
  '-',
  'mute',
  'unmute',
  'clear',
  'clear playback',
  'clear all',
  'copy error',
  'version',
  'open now-playing',
  'open visualizer',
  'open controls',
  'visualizer ascii',
  'theme list',
  'theme use default',
  'theme use tokyo-night',
  'theme use dark-soul',
  'theme use synthwave',
  'theme use dark-petroleum-blue',
  'theme use shell-pink',
  'settings radio.static on',
  'settings radio.static off',
]
